"""
美股公司名称配置模块
提供统一的股票代码-公司名称映射，支持中英文名称和关键词检索。
默认数据内嵌于模块中，可通过 reload_config(path) 从外部 JSON 文件覆盖。
"""

import json
from typing import Dict, List, Optional

_DEFAULT_CONFIG: Dict = {
    "AAPL": {"en": "Apple", "zh": "苹果公司", "keywords": ["apple", "iphone", "ipad", "mac"]},
    "MSFT": {"en": "Microsoft", "zh": "微软", "keywords": ["microsoft", "windows", "azure"]},
    "GOOGL": {"en": "Google", "zh": "谷歌", "keywords": ["google", "alphabet", "search"]},
    "AMZN": {"en": "Amazon", "zh": "亚马逊", "keywords": ["amazon", "aws", "prime"]},
    "TSLA": {"en": "Tesla", "zh": "特斯拉", "keywords": ["tesla", "elon musk", "electric vehicle"]},
    "NVDA": {"en": "NVIDIA", "zh": "英伟达", "keywords": ["nvidia", "gpu", "ai chip"]},
    "META": {"en": "Meta", "zh": "Meta", "keywords": ["meta", "facebook", "instagram", "whatsapp"]},
    "NFLX": {"en": "Netflix", "zh": "奈飞", "keywords": ["netflix", "streaming"]},
    "TSM": {"en": "TSMC", "zh": "台积电", "keywords": ["tsmc", "taiwan semiconductor"]},
    "JPM": {"en": "JPMorgan Chase", "zh": "摩根大通", "keywords": ["jpmorgan", "jp morgan", "chase"]},
    "JNJ": {"en": "Johnson & Johnson", "zh": "强生", "keywords": ["johnson & johnson", "jnj"]},
    "V": {"en": "Visa", "zh": "Visa", "keywords": ["visa"]},
    "WMT": {"en": "Walmart", "zh": "沃尔玛", "keywords": ["walmart"]},
    "AMD": {"en": "AMD", "zh": "AMD", "keywords": ["amd", "ryzen", "radeon"]},
    "INTC": {"en": "Intel", "zh": "英特尔", "keywords": ["intel"]},
    "QCOM": {"en": "Qualcomm", "zh": "高通", "keywords": ["qualcomm", "snapdragon"]},
    "BABA": {"en": "Alibaba", "zh": "阿里巴巴", "keywords": ["alibaba", "aliexpress"]},
    "ADBE": {"en": "Adobe", "zh": "Adobe", "keywords": ["adobe", "photoshop"]},
    "CRM": {"en": "Salesforce", "zh": "Salesforce", "keywords": ["salesforce"]},
    "PYPL": {"en": "PayPal", "zh": "PayPal", "keywords": ["paypal"]},
    "PLTR": {"en": "Palantir", "zh": "Palantir", "keywords": ["palantir"]},
    "MU": {"en": "Micron", "zh": "美光", "keywords": ["micron"]},
    "SQ": {"en": "Block", "zh": "Block", "keywords": ["block", "square", "cash app"]},
    "ZM": {"en": "Zoom", "zh": "Zoom", "keywords": ["zoom"]},
    "CSCO": {"en": "Cisco", "zh": "思科", "keywords": ["cisco"]},
    "SHOP": {"en": "Shopify", "zh": "Shopify", "keywords": ["shopify"]},
    "ORCL": {"en": "Oracle", "zh": "甲骨文", "keywords": ["oracle"]},
    "X": {"en": "X", "zh": "X", "keywords": ["twitter", "x corp"]},
    "SPOT": {"en": "Spotify", "zh": "Spotify", "keywords": ["spotify"]},
    "AVGO": {"en": "Broadcom", "zh": "博通", "keywords": ["broadcom"]},
    "ASML": {"en": "ASML", "zh": "ASML", "keywords": ["asml"]},
    "TWLO": {"en": "Twilio", "zh": "Twilio", "keywords": ["twilio"]},
    "SNAP": {"en": "Snap Inc.", "zh": "Snap", "keywords": ["snapchat", "snap"]},
    "TEAM": {"en": "Atlassian", "zh": "Atlassian", "keywords": ["atlassian", "jira", "confluence"]},
    "SQSP": {"en": "Squarespace", "zh": "Squarespace", "keywords": ["squarespace"]},
    "UBER": {"en": "Uber", "zh": "Uber", "keywords": ["uber"]},
    "ROKU": {"en": "Roku", "zh": "Roku", "keywords": ["roku"]},
    "PINS": {"en": "Pinterest", "zh": "Pinterest", "keywords": ["pinterest"]},
    # Major Index ETFs
    "SPY": {"en": "SPDR S&P 500 ETF Trust", "zh": "标普500 ETF", "keywords": ["spy", "spdr", "s&p 500", "sp500"]},
    "QQQ": {"en": "Invesco QQQ Trust", "zh": "纳斯达克100 ETF", "keywords": ["qqq", "nasdaq 100", "invesco"]},
    "DIA": {"en": "SPDR Dow Jones Industrial Average ETF", "zh": "道琼斯 ETF", "keywords": ["dia", "dow jones", "djia"]},
    "IWM": {"en": "iShares Russell 2000 ETF", "zh": "罗素2000 ETF", "keywords": ["iwm", "russell 2000", "ishares"]},
    "VTI": {"en": "Vanguard Total Stock Market ETF", "zh": "全股市 ETF", "keywords": ["vti", "vanguard", "total stock market"]},
    "VO": {"en": "Vanguard Mid-Cap ETF", "zh": "中盘股 ETF", "keywords": ["vo", "vanguard", "mid-cap"]},
    "VB": {"en": "Vanguard Small-Cap ETF", "zh": "小盘股 ETF", "keywords": ["vb", "vanguard", "small-cap"]},
    "VGT": {"en": "Vanguard Information Technology ETF", "zh": "信息技术 ETF", "keywords": ["vgt", "vanguard", "information technology"]},
    "XLF": {"en": "Financial Select Sector SPDR Fund", "zh": "金融板块 ETF", "keywords": ["xlf", "financial", "spdr"]},
    "XLE": {"en": "Energy Select Sector SPDR Fund", "zh": "能源板块 ETF", "keywords": ["xle", "energy", "spdr"]},
    "XLK": {"en": "Technology Select Sector SPDR Fund", "zh": "科技板块 ETF", "keywords": ["xlk", "technology", "spdr"]},
    "XLV": {"en": "Health Care Select Sector SPDR Fund", "zh": "医疗保健 ETF", "keywords": ["xlv", "health care", "spdr"]},
    "ARKK": {"en": "ARK Innovation ETF", "zh": "ARK创新 ETF", "keywords": ["arkk", "ark", "innovation", "cathie wood"]},
    "SOXX": {"en": "iShares Semiconductor ETF", "zh": "半导体 ETF", "keywords": ["soxx", "semiconductor", "ishares"]},
    "IBB": {"en": "iShares Biotechnology ETF", "zh": "生物科技 ETF", "keywords": ["ibb", "biotechnology", "ishares"]},
    "GLD": {"en": "SPDR Gold Shares", "zh": "黄金 ETF", "keywords": ["gld", "gold", "spdr"]},
    "SLV": {"en": "iShares Silver Trust", "zh": "白银 ETF", "keywords": ["slv", "silver", "ishares"]},
    "USO": {"en": "United States Oil Fund", "zh": "石油 ETF", "keywords": ["uso", "oil", "crude"]},
    "TLT": {"en": "iShares 20+ Year Treasury Bond ETF", "zh": "长期国债 ETF", "keywords": ["tlt", "treasury", "bond", "20 year"]},
    "QQQM": {"en": "Invesco NASDAQ 100 ETF", "zh": "纳斯达克100 ETF (低成本)", "keywords": ["qqqm", "nasdaq 100", "invesco", "low cost"]},
    # NASDAQ 100 Components
    "GOOG": {"en": "Alphabet Inc. (Class C)", "zh": "谷歌(无投票权)", "keywords": ["google", "alphabet", "goog"]},
    "COST": {"en": "Costco", "zh": "好市多", "keywords": ["costco", "wholesale"]},
    "PEP": {"en": "PepsiCo", "zh": "百事公司", "keywords": ["pepsi", "pepsico", "frito-lay"]},
    "CMCSA": {"en": "Comcast", "zh": "康卡斯特", "keywords": ["comcast", "nbcuniversal", "xfinity"]},
    "TXN": {"en": "Texas Instruments", "zh": "德州仪器", "keywords": ["texas instruments", "ti"]},
    "AMGN": {"en": "Amgen", "zh": "安进", "keywords": ["amgen", "biotech"]},
    "HON": {"en": "Honeywell", "zh": "霍尼韦尔", "keywords": ["honeywell"]},
    "INTU": {"en": "Intuit", "zh": "财捷", "keywords": ["intuit", "turbotax", "quickbooks"]},
    "AMAT": {"en": "Applied Materials", "zh": "应用材料", "keywords": ["applied materials"]},
    "BKNG": {"en": "Booking Holdings", "zh": "缤客", "keywords": ["booking", "priceline", "kayak"]},
    "ISRG": {"en": "Intuitive Surgical", "zh": "直觉外科", "keywords": ["intuitive surgical", "da vinci"]},
    "SBUX": {"en": "Starbucks", "zh": "星巴克", "keywords": ["starbucks", "coffee"]},
    "MDLZ": {"en": "Mondelez International", "zh": "亿滋国际", "keywords": ["mondelez", "oreo", "cadbury"]},
    "GILD": {"en": "Gilead Sciences", "zh": "吉利德科学", "keywords": ["gilead", "hiv", "hepatitis"]},
    "ADP": {"en": "Automatic Data Processing", "zh": "自动数据处理", "keywords": ["adp", "payroll"]},
    "LRCX": {"en": "Lam Research", "zh": "泛林集团", "keywords": ["lam research", "semiconductor equipment"]},
    "REGN": {"en": "Regeneron", "zh": "再生元", "keywords": ["regeneron", "biotech"]},
    "VRTX": {"en": "Vertex Pharmaceuticals", "zh": "福泰制药", "keywords": ["vertex", "cystic fibrosis"]},
    "FISV": {"en": "Fiserv", "zh": "费哲金融服务", "keywords": ["fiserv", "fintech"]},
    "KLAC": {"en": "KLA Corporation", "zh": "科磊", "keywords": ["kla", "semiconductor inspection"]},
    "SNPS": {"en": "Synopsys", "zh": "新思科技", "keywords": ["synopsys", "eda"]},
    "CDNS": {"en": "Cadence Design Systems", "zh": "楷登电子", "keywords": ["cadence", "eda"]},
    "NXPI": {"en": "NXP Semiconductors", "zh": "恩智浦半导体", "keywords": ["nxp", "semiconductor"]},
    "MRVL": {"en": "Marvell Technology", "zh": "迈威尔科技", "keywords": ["marvell"]},
    "ORLY": {"en": "O'Reilly Automotive", "zh": "奥莱利汽车", "keywords": ["oreilly", "auto parts"]},
    "CSX": {"en": "CSX Corporation", "zh": "CSX运输", "keywords": ["csx", "railroad"]},
    "MAR": {"en": "Marriott International", "zh": "万豪国际", "keywords": ["marriott", "hotel"]},
    "MELI": {"en": "MercadoLibre", "zh": "自由市场", "keywords": ["mercadolibre", "ecommerce", "latam"]},
    "CTAS": {"en": "Cintas Corporation", "zh": "辛塔斯", "keywords": ["cintas", "uniforms"]},
    "PAYX": {"en": "Paychex", "zh": "沛齐", "keywords": ["paychex", "payroll"]},
    "CHTR": {"en": "Charter Communications", "zh": "特许通讯", "keywords": ["charter", "spectrum"]},
    "ABNB": {"en": "Airbnb", "zh": "爱彼迎", "keywords": ["airbnb", "vacation rental"]},
    "DXCM": {"en": "DexCom", "zh": "德康医疗", "keywords": ["dexcom", "cgm", "glucose monitor"]},
    "IDXX": {"en": "IDEXX Laboratories", "zh": "爱德士", "keywords": ["idexx", "veterinary"]},
    "PCAR": {"en": "PACCAR", "zh": "帕卡", "keywords": ["paccar", "kenworth", "peterbilt"]},
    "MNST": {"en": "Monster Beverage", "zh": "怪兽饮料", "keywords": ["monster", "energy drink"]},
    "AZN": {"en": "AstraZeneca", "zh": "阿斯利康", "keywords": ["astrazeneca", "pharma"]},
    "BIIB": {"en": "Biogen", "zh": "百健", "keywords": ["biogen", "alzheimer"]},
    "ALGN": {"en": "Align Technology", "zh": "隐适美", "keywords": ["align", "invisalign"]},
    "SIRI": {"en": "Sirius XM", "zh": "天狼星XM", "keywords": ["sirius", "satellite radio"]},
    "VRSK": {"en": "Verisk Analytics", "zh": "韦睿司", "keywords": ["verisk", "analytics"]},
    "CCEP": {"en": "Coca-Cola Europacific Partners", "zh": "可口可乐欧洲太平洋", "keywords": ["coca-cola", "coke", "bottler"]},
    "CPRT": {"en": "Copart", "zh": "科帕特", "keywords": ["copart", "auto auction"]},
    "MCHP": {"en": "Microchip Technology", "zh": "微芯科技", "keywords": ["microchip", "mcu"]},
    "TTD": {"en": "The Trade Desk", "zh": "广告达人", "keywords": ["trade desk", "adtech"]},
    "PDD": {"en": "PDD Holdings", "zh": "拼多多", "keywords": ["pinduoduo", "pdd", "temu"]},
    "XEL": {"en": "Xcel Energy", "zh": "Xcel能源", "keywords": ["xcel", "utility"]},
    "EXC": {"en": "Exelon", "zh": "爱克斯龙", "keywords": ["exelon", "utility"]},
    "AEP": {"en": "American Electric Power", "zh": "美国电力", "keywords": ["aep", "electric utility"]},
    "EA": {"en": "Electronic Arts", "zh": "艺电", "keywords": ["ea", "electronic arts", "fifa", "madden"]},
    "CTSH": {"en": "Cognizant", "zh": "高知特", "keywords": ["cognizant", "it services"]},
    "ZS": {"en": "Zscaler", "zh": "Zscaler", "keywords": ["zscaler", "cybersecurity", "zero trust"]},
    "FAST": {"en": "Fastenal", "zh": "快扣", "keywords": ["fastenal", "industrial supply"]},
    "ANSS": {"en": "ANSYS", "zh": "ANSYS", "keywords": ["ansys", "simulation"]},
    "BKR": {"en": "Baker Hughes", "zh": "贝克休斯", "keywords": ["baker hughes", "oilfield"]},
    "DDOG": {"en": "Datadog", "zh": "Datadog", "keywords": ["datadog", "monitoring", "observability"]},
    "ODFL": {"en": "Old Dominion Freight Line", "zh": "老自治领货运", "keywords": ["old dominion", "trucking"]},
    "GFS": {"en": "GlobalFoundries", "zh": "格芯", "keywords": ["globalfoundries", "semiconductor foundry"]},
    "ROST": {"en": "Ross Stores", "zh": "罗斯百货", "keywords": ["ross", "discount retail"]},
    "LULU": {"en": "Lululemon", "zh": "露露乐蒙", "keywords": ["lululemon", "athleisure"]},
    "VRSN": {"en": "VeriSign", "zh": "威瑞信", "keywords": ["verisign", "dns", "domain"]},
    "CSGP": {"en": "CoStar Group", "zh": "科斯塔集团", "keywords": ["costar", "real estate data"]},
    "ON": {"en": "ON Semiconductor", "zh": "安森美半导体", "keywords": ["on semiconductor", "onsemi"]},
    "CRWD": {"en": "CrowdStrike", "zh": "CrowdStrike", "keywords": ["crowdstrike", "cybersecurity", "endpoint"]},
    "SMCI": {"en": "Super Micro Computer", "zh": "超微电脑", "keywords": ["supermicro", "server"]},
    "TROW": {"en": "T. Rowe Price", "zh": "普信集团", "keywords": ["t rowe price", "asset management"]},
    "FANG": {"en": "Diamondback Energy", "zh": "响尾蛇能源", "keywords": ["diamondback", "oil", "permian"]},
    "GEHC": {"en": "GE HealthCare", "zh": "GE医疗", "keywords": ["ge healthcare", "medical imaging"]},
    "MPWR": {"en": "Monolithic Power Systems", "zh": "芯源系统", "keywords": ["monolithic power", "mps"]},
    "MNDY": {"en": "monday.com", "zh": "monday.com", "keywords": ["monday", "project management"]},
    "KDP": {"en": "Keurig Dr Pepper", "zh": "胡椒博士", "keywords": ["keurig", "dr pepper", "coffee"]},
    "ENPH": {"en": "Enphase Energy", "zh": "Enphase能源", "keywords": ["enphase", "solar", "microinverter"]},
    "DLTR": {"en": "Dollar Tree", "zh": "美元树", "keywords": ["dollar tree", "discount store"]},
    "PTON": {"en": "Peloton", "zh": "Peloton", "keywords": ["peloton", "fitness", "bike"]},
    # S&P 500 Components - Information Technology
    "ORCL": {"en": "Oracle", "zh": "甲骨文", "keywords": ["oracle", "database", "cloud"]},
    "CRM": {"en": "Salesforce", "zh": "Salesforce", "keywords": ["salesforce", "crm"]},
    "ADBE": {"en": "Adobe", "zh": "Adobe", "keywords": ["adobe", "photoshop", "creative cloud"]},
    "CSCO": {"en": "Cisco", "zh": "思科", "keywords": ["cisco", "networking"]},
    "ACN": {"en": "Accenture", "zh": "埃森哲", "keywords": ["accenture", "consulting"]},
    "IBM": {"en": "IBM", "zh": "IBM", "keywords": ["ibm", "international business machines"]},
    "NOW": {"en": "ServiceNow", "zh": "ServiceNow", "keywords": ["servicenow", "workflow"]},
    "AMD": {"en": "AMD", "zh": "AMD", "keywords": ["amd", "ryzen", "radeon"]},
    "INTU": {"en": "Intuit", "zh": "财捷", "keywords": ["intuit", "turbotax", "quickbooks"]},
    "AMAT": {"en": "Applied Materials", "zh": "应用材料", "keywords": ["applied materials"]},
    "LRCX": {"en": "Lam Research", "zh": "泛林集团", "keywords": ["lam research", "semiconductor equipment"]},
    "KLAC": {"en": "KLA Corporation", "zh": "科磊", "keywords": ["kla", "semiconductor inspection"]},
    "SNPS": {"en": "Synopsys", "zh": "新思科技", "keywords": ["synopsys", "eda"]},
    "CDNS": {"en": "Cadence Design Systems", "zh": "楷登电子", "keywords": ["cadence", "eda"]},
    "MRVL": {"en": "Marvell Technology", "zh": "迈威尔科技", "keywords": ["marvell"]},
    "NXPI": {"en": "NXP Semiconductors", "zh": "恩智浦半导体", "keywords": ["nxp", "semiconductor"]},
    "MCHP": {"en": "Microchip Technology", "zh": "微芯科技", "keywords": ["microchip", "mcu"]},
    "FTNT": {"en": "Fortinet", "zh": "飞塔信息", "keywords": ["fortinet", "cybersecurity"]},
    "PANW": {"en": "Palo Alto Networks", "zh": "派拓网络", "keywords": ["palo alto", "cybersecurity"]},
    "MSCI": {"en": "MSCI", "zh": "MSCI", "keywords": ["msci", "index"]},
    "FICO": {"en": "Fair Isaac", "zh": "费埃哲", "keywords": ["fico", "credit score"]},
    "HPQ": {"en": "HP Inc.", "zh": "惠普", "keywords": ["hp", "printer", "pc"]},
    "HPE": {"en": "Hewlett Packard Enterprise", "zh": "慧与", "keywords": ["hpe", "enterprise"]},
    "GLW": {"en": "Corning", "zh": "康宁", "keywords": ["corning", "glass", "fiber"]},
    "APH": {"en": "Amphenol", "zh": "安费诺", "keywords": ["amphenol", "connectors"]},
    "KEYS": {"en": "Keysight Technologies", "zh": "是德科技", "keywords": ["keysight", "testing"]},
    "ANSS": {"en": "ANSYS", "zh": "ANSYS", "keywords": ["ansys", "simulation"]},
    "IT": {"en": "Gartner", "zh": "高德纳", "keywords": ["gartner", "research"]},
    "VRSN": {"en": "VeriSign", "zh": "威瑞信", "keywords": ["verisign", "dns", "domain"]},
    "GDDY": {"en": "GoDaddy", "zh": "GoDaddy", "keywords": ["godaddy", "domain", "hosting"]},
    "TYL": {"en": "Tyler Technologies", "zh": "泰勒科技", "keywords": ["tyler", "government software"]},
    "EPAM": {"en": "EPAM Systems", "zh": "EPAM系统", "keywords": ["epam", "software"]},
    "CDW": {"en": "CDW Corporation", "zh": "CDW", "keywords": ["cdw", "it solutions"]},
    "GEN": {"en": "Gen Digital", "zh": "Gen数字", "keywords": ["norton", "lifelock", "avast"]},
    "STX": {"en": "Seagate Technology", "zh": "希捷科技", "keywords": ["seagate", "hard drive"]},
    "WDC": {"en": "Western Digital", "zh": "西部数据", "keywords": ["western digital", "hard drive"]},
    # S&P 500 Components - Health Care
    "UNH": {"en": "UnitedHealth Group", "zh": "联合健康", "keywords": ["unitedhealth", "health insurance"]},
    "JNJ": {"en": "Johnson & Johnson", "zh": "强生", "keywords": ["johnson & johnson", "jnj"]},
    "LLY": {"en": "Eli Lilly", "zh": "礼来", "keywords": ["eli lilly", "pharma"]},
    "PFE": {"en": "Pfizer", "zh": "辉瑞", "keywords": ["pfizer", "pharma"]},
    "ABBV": {"en": "AbbVie", "zh": "艾伯维", "keywords": ["abbvie", "pharma"]},
    "MRK": {"en": "Merck", "zh": "默克", "keywords": ["merck", "pharma"]},
    "TMO": {"en": "Thermo Fisher Scientific", "zh": "赛默飞", "keywords": ["thermo fisher", "lab equipment"]},
    "ABT": {"en": "Abbott Laboratories", "zh": "雅培", "keywords": ["abbott", "medical devices"]},
    "DHR": {"en": "Danaher", "zh": "丹纳赫", "keywords": ["danaher", "life sciences"]},
    "BMY": {"en": "Bristol-Myers Squibb", "zh": "百时美施贵宝", "keywords": ["bristol-myers", "pharma"]},
    "AMGN": {"en": "Amgen", "zh": "安进", "keywords": ["amgen", "biotech"]},
    "GILD": {"en": "Gilead Sciences", "zh": "吉利德科学", "keywords": ["gilead", "hiv", "hepatitis"]},
    "MDT": {"en": "Medtronic", "zh": "美敦力", "keywords": ["medtronic", "medical devices"]},
    "SYK": {"en": "Stryker", "zh": "史赛克", "keywords": ["stryker", "medical devices"]},
    "BSX": {"en": "Boston Scientific", "zh": "波士顿科学", "keywords": ["boston scientific", "medical devices"]},
    "ISRG": {"en": "Intuitive Surgical", "zh": "直觉外科", "keywords": ["intuitive surgical", "da vinci"]},
    "ZTS": {"en": "Zoetis", "zh": "硕腾", "keywords": ["zoetis", "animal health"]},
    "REGN": {"en": "Regeneron", "zh": "再生元", "keywords": ["regeneron", "biotech"]},
    "VRTX": {"en": "Vertex Pharmaceuticals", "zh": "福泰制药", "keywords": ["vertex", "cystic fibrosis"]},
    "EW": {"en": "Edwards Lifesciences", "zh": "爱德华生命科学", "keywords": ["edwards", "heart valve"]},
    "BIIB": {"en": "Biogen", "zh": "百健", "keywords": ["biogen", "alzheimer"]},
    "IDXX": {"en": "IDEXX Laboratories", "zh": "爱德士", "keywords": ["idexx", "veterinary"]},
    "DXCM": {"en": "DexCom", "zh": "德康医疗", "keywords": ["dexcom", "cgm", "glucose monitor"]},
    "HOLX": {"en": "Hologic", "zh": "豪洛捷", "keywords": ["hologic", "mammography"]},
    "ALGN": {"en": "Align Technology", "zh": "隐适美", "keywords": ["align", "invisalign"]},
    "IQV": {"en": "IQVIA", "zh": "艾昆纬", "keywords": ["iqvia", "clinical research"]},
    "A": {"en": "Agilent Technologies", "zh": "安捷伦", "keywords": ["agilent", "lab instruments"]},
    "BIO": {"en": "Bio-Rad Laboratories", "zh": "伯乐实验室", "keywords": ["bio-rad", "life science"]},
    "MTD": {"en": "Mettler-Toledo", "zh": "梅特勒-托利多", "keywords": ["mettler", "weighing"]},
    "WAT": {"en": "Waters Corporation", "zh": "沃特世", "keywords": ["waters", "chromatography"]},
    "RMD": {"en": "ResMed", "zh": "瑞思迈", "keywords": ["resmed", "sleep apnea"]},
    "BAX": {"en": "Baxter International", "zh": "百特国际", "keywords": ["baxter", "dialysis"]},
    "BDX": {"en": "Becton Dickinson", "zh": "碧迪", "keywords": ["becton dickinson", "bd", "syringe"]},
    "ZBH": {"en": "Zimmer Biomet", "zh": "捷迈邦美", "keywords": ["zimmer", "orthopedic"]},
    "HCA": {"en": "HCA Healthcare", "zh": "HCA医疗", "keywords": ["hca", "hospital"]},
    "CNC": {"en": "Centene", "zh": "森特尼", "keywords": ["centene", "healthcare"]},
    "MOH": {"en": "Molina Healthcare", "zh": "莫利纳医疗", "keywords": ["molina", "healthcare"]},
    "CI": {"en": "Cigna", "zh": "信诺", "keywords": ["cigna", "health insurance"]},
    "ELV": {"en": "Elevance Health", "zh": "Elevance健康", "keywords": ["elevance", "anthem", "health insurance"]},
    "HUM": {"en": "Humana", "zh": "哈门那", "keywords": ["humana", "health insurance"]},
    "CVS": {"en": "CVS Health", "zh": "CVS健康", "keywords": ["cvs", "pharmacy"]},
    "WST": {"en": "West Pharmaceutical Services", "zh": "西氏医药", "keywords": ["west pharma", "packaging"]},
    "VTRS": {"en": "Viatris", "zh": "晖致", "keywords": ["viatris", "generics"]},
    "OGN": {"en": "Organon", "zh": "欧加农", "keywords": ["organon", "pharma"]},
    # S&P 500 Components - Financials
    "BRK.B": {"en": "Berkshire Hathaway", "zh": "伯克希尔哈撒韦", "keywords": ["berkshire", "warren buffett"]},
    "JPM": {"en": "JPMorgan Chase", "zh": "摩根大通", "keywords": ["jpmorgan", "jp morgan", "chase"]},
    "V": {"en": "Visa", "zh": "Visa", "keywords": ["visa"]},
    "MA": {"en": "Mastercard", "zh": "万事达", "keywords": ["mastercard"]},
    "BAC": {"en": "Bank of America", "zh": "美国银行", "keywords": ["bank of america", "boa"]},
    "WFC": {"en": "Wells Fargo", "zh": "富国银行", "keywords": ["wells fargo"]},
    "GS": {"en": "Goldman Sachs", "zh": "高盛", "keywords": ["goldman sachs"]},
    "MS": {"en": "Morgan Stanley", "zh": "摩根士丹利", "keywords": ["morgan stanley"]},
    "AXP": {"en": "American Express", "zh": "美国运通", "keywords": ["american express", "amex"]},
    "SPGI": {"en": "S&P Global", "zh": "标普全球", "keywords": ["s&p global", "ratings"]},
    "BLK": {"en": "BlackRock", "zh": "贝莱德", "keywords": ["blackrock", "asset management"]},
    "SCHW": {"en": "Charles Schwab", "zh": "嘉信理财", "keywords": ["schwab", "brokerage"]},
    "C": {"en": "Citigroup", "zh": "花旗集团", "keywords": ["citigroup", "citi"]},
    "PGR": {"en": "Progressive", "zh": "前进保险", "keywords": ["progressive", "insurance"]},
    "CB": {"en": "Chubb", "zh": "安达保险", "keywords": ["chubb", "insurance"]},
    "MMC": {"en": "Marsh & McLennan", "zh": "威达信", "keywords": ["marsh", "insurance broker"]},
    "AON": {"en": "Aon", "zh": "怡安", "keywords": ["aon", "insurance"]},
    "ICE": {"en": "Intercontinental Exchange", "zh": "洲际交易所", "keywords": ["ice", "nyse", "exchange"]},
    "CME": {"en": "CME Group", "zh": "芝商所", "keywords": ["cme", "futures", "exchange"]},
    "MCO": {"en": "Moody's", "zh": "穆迪", "keywords": ["moodys", "ratings"]},
    "FIS": {"en": "Fidelity National Information Services", "zh": "富达国民信息", "keywords": ["fis", "fintech"]},
    "FISV": {"en": "Fiserv", "zh": "费哲金融服务", "keywords": ["fiserv", "fintech"]},
    "FDS": {"en": "FactSet", "zh": "FactSet", "keywords": ["factset", "financial data"]},
    "NDAQ": {"en": "Nasdaq", "zh": "纳斯达克", "keywords": ["nasdaq", "exchange"]},
    "CINF": {"en": "Cincinnati Financial", "zh": "辛辛那提金融", "keywords": ["cincinnati financial", "insurance"]},
    "TRV": {"en": "Travelers", "zh": "旅行者保险", "keywords": ["travelers", "insurance"]},
    "ALL": {"en": "Allstate", "zh": "好事达", "keywords": ["allstate", "insurance"]},
    "AFL": {"en": "Aflac", "zh": "阿弗拉克", "keywords": ["aflac", "insurance"]},
    "MET": {"en": "MetLife", "zh": "大都会人寿", "keywords": ["metlife", "insurance"]},
    "PRU": {"en": "Prudential Financial", "zh": "保德信金融", "keywords": ["prudential", "insurance"]},
    "AIG": {"en": "American International Group", "zh": "美国国际集团", "keywords": ["aig", "insurance"]},
    "AJG": {"en": "Arthur J. Gallagher", "zh": "亚瑟加拉格尔", "keywords": ["gallagher", "insurance"]},
    "AIZ": {"en": "Assurant", "zh": "亚瑟蓝特", "keywords": ["assurant", "insurance"]},
    "BRO": {"en": "Brown & Brown", "zh": "布朗&布朗", "keywords": ["brown", "insurance"]},
    "ERIE": {"en": "Erie Indemnity", "zh": "伊利赔偿", "keywords": ["erie", "insurance"]},
    "HBAN": {"en": "Huntington Bancshares", "zh": "亨廷顿银行", "keywords": ["huntington", "bank"]},
    "KEY": {"en": "KeyCorp", "zh": "Key银行", "keywords": ["keycorp", "bank"]},
    "MTB": {"en": "M&T Bank", "zh": "M&T银行", "keywords": ["m&t", "bank"]},
    "PNC": {"en": "PNC Financial", "zh": "PNC金融", "keywords": ["pnc", "bank"]},
    "RF": {"en": "Regions Financial", "zh": "区域金融", "keywords": ["regions", "bank"]},
    "STT": {"en": "State Street", "zh": "道富", "keywords": ["state street", "bank"]},
    "USB": {"en": "U.S. Bancorp", "zh": "美国合众银行", "keywords": ["us bank", "bancorp"]},
    "ZION": {"en": "Zions Bancorporation", "zh": "锡安银行", "keywords": ["zions", "bank"]},
    "CFG": {"en": "Citizens Financial", "zh": "公民金融", "keywords": ["citizens", "bank"]},
    "FITB": {"en": "Fifth Third Bancorp", "zh": "五三银行", "keywords": ["fifth third", "bank"]},
    "CMA": {"en": "Comerica", "zh": "科美利加", "keywords": ["comerica", "bank"]},
    "EWBC": {"en": "East West Bancorp", "zh": "华美银行", "keywords": ["east west", "bank"]},
    "FHN": {"en": "First Horizon", "zh": "第一地平线", "keywords": ["first horizon", "bank"]},
    "WAL": {"en": "Western Alliance", "zh": "西部联盟", "keywords": ["western alliance", "bank"]},
    "PNFP": {"en": "Pinnacle Financial", "zh": "尖峰金融", "keywords": ["pinnacle", "bank"]},
    "COLB": {"en": "Columbia Banking", "zh": "哥伦比亚银行", "keywords": ["columbia", "bank"]},
    "UMBF": {"en": "UMB Financial", "zh": "UMB金融", "keywords": ["umb", "bank"]},
    "WTFC": {"en": "Wintrust Financial", "zh": "温特拉斯特", "keywords": ["wintrust", "bank"]},
    # S&P 500 Components - Consumer Discretionary
    "AMZN": {"en": "Amazon", "zh": "亚马逊", "keywords": ["amazon", "aws", "prime"]},
    "TSLA": {"en": "Tesla", "zh": "特斯拉", "keywords": ["tesla", "elon musk", "electric vehicle"]},
    "HD": {"en": "Home Depot", "zh": "家得宝", "keywords": ["home depot", "hardware"]},
    "MCD": {"en": "McDonald's", "zh": "麦当劳", "keywords": ["mcdonalds", "fast food"]},
    "NKE": {"en": "Nike", "zh": "耐克", "keywords": ["nike", "shoes", "sportswear"]},
    "LOW": {"en": "Lowe's", "zh": "劳氏", "keywords": ["lowes", "hardware"]},
    "TJX": {"en": "TJX Companies", "zh": "TJX", "keywords": ["tj maxx", "marshalls"]},
    "SBUX": {"en": "Starbucks", "zh": "星巴克", "keywords": ["starbucks", "coffee"]},
    "TGT": {"en": "Target", "zh": "塔吉特", "keywords": ["target", "retail"]},
    "DG": {"en": "Dollar General", "zh": "美元将军", "keywords": ["dollar general", "discount"]},
    "ROST": {"en": "Ross Stores", "zh": "罗斯百货", "keywords": ["ross", "discount retail"]},
    "ORLY": {"en": "O'Reilly Automotive", "zh": "奥莱利汽车", "keywords": ["oreilly", "auto parts"]},
    "AZO": {"en": "AutoZone", "zh": "汽车地带", "keywords": ["autozone", "auto parts"]},
    "CMG": {"en": "Chipotle Mexican Grill", "zh": "奇波雷", "keywords": ["chipotle", "mexican food"]},
    "YUM": {"en": "Yum! Brands", "zh": "百胜餐饮", "keywords": ["yum", "kfc", "taco bell", "pizza hut"]},
    "DHI": {"en": "D.R. Horton", "zh": "霍顿房屋", "keywords": ["horton", "homebuilder"]},
    "LEN": {"en": "Lennar", "zh": "莱纳", "keywords": ["lennar", "homebuilder"]},
    "NVR": {"en": "NVR", "zh": "NVR", "keywords": ["nvr", "homebuilder"]},
    "PHM": {"en": "PulteGroup", "zh": "普尔特房屋", "keywords": ["pulte", "homebuilder"]},
    "TOL": {"en": "Toll Brothers", "zh": "托尔兄弟", "keywords": ["toll brothers", "homebuilder"]},
    "M": {"en": "Macy's", "zh": "梅西百货", "keywords": ["macys", "department store"]},
    "KSS": {"en": "Kohl's", "zh": "科尔士", "keywords": ["kohls", "department store"]},
    "GPS": {"en": "Gap Inc.", "zh": "盖璞", "keywords": ["gap", "clothing"]},
    "ANF": {"en": "Abercrombie & Fitch", "zh": "阿贝克隆比", "keywords": ["abercrombie", "clothing"]},
    "AEO": {"en": "American Eagle Outfitters", "zh": "美国鹰", "keywords": ["american eagle", "clothing"]},
    "URBN": {"en": "Urban Outfitters", "zh": "Urban Outfitters", "keywords": ["urban outfitters", "clothing"]},
    "BBWI": {"en": "Bath & Body Works", "zh": "沐浴美体", "keywords": ["bath body works", "candles"]},
    "BBY": {"en": "Best Buy", "zh": "百思买", "keywords": ["best buy", "electronics"]},
    "EBAY": {"en": "eBay", "zh": "eBay", "keywords": ["ebay", "auction", "marketplace"]},
    "ETSY": {"en": "Etsy", "zh": "Etsy", "keywords": ["etsy", "handmade"]},
    "ABNB": {"en": "Airbnb", "zh": "爱彼迎", "keywords": ["airbnb", "vacation rental"]},
    "BKNG": {"en": "Booking Holdings", "zh": "缤客", "keywords": ["booking", "priceline", "kayak"]},
    "MAR": {"en": "Marriott International", "zh": "万豪国际", "keywords": ["marriott", "hotel"]},
    "HLT": {"en": "Hilton", "zh": "希尔顿", "keywords": ["hilton", "hotel"]},
    "WH": {"en": "Wyndham Hotels", "zh": "温德姆酒店", "keywords": ["wyndham", "hotel"]},
    "LVS": {"en": "Las Vegas Sands", "zh": "拉斯维加斯金沙", "keywords": ["las vegas sands", "casino"]},
    "MGM": {"en": "MGM Resorts", "zh": "美高梅", "keywords": ["mgm", "casino"]},
    "WYNN": {"en": "Wynn Resorts", "zh": "永利度假村", "keywords": ["wynn", "casino"]},
    "CCL": {"en": "Carnival", "zh": "嘉年华邮轮", "keywords": ["carnival", "cruise"]},
    "RCL": {"en": "Royal Caribbean", "zh": "皇家加勒比", "keywords": ["royal caribbean", "cruise"]},
    "NCLH": {"en": "Norwegian Cruise Line", "zh": "挪威邮轮", "keywords": ["norwegian", "cruise"]},
    "ROKU": {"en": "Roku", "zh": "Roku", "keywords": ["roku", "streaming"]},
    "DIS": {"en": "Walt Disney", "zh": "迪士尼", "keywords": ["disney", "entertainment"]},
    "FOX": {"en": "Fox Corporation", "zh": "福克斯", "keywords": ["fox", "media"]},
    "FOXA": {"en": "Fox Corporation (Class A)", "zh": "福克斯(A类)", "keywords": ["fox", "media"]},
    "LUMN": {"en": "Lumen Technologies", "zh": "Lumen科技", "keywords": ["lumen", "centurylink", "telecom"]},
    "GM": {"en": "General Motors", "zh": "通用汽车", "keywords": ["general motors", "gm", "chevrolet"]},
    "F": {"en": "Ford Motor", "zh": "福特汽车", "keywords": ["ford", "automobile"]},
    "HOG": {"en": "Harley-Davidson", "zh": "哈雷戴维森", "keywords": ["harley", "motorcycle"]},
    "TPX": {"en": "Tempur Sealy", "zh": "泰普尔", "keywords": ["tempur", "mattress"]},
    "HAS": {"en": "Hasbro", "zh": "孩之宝", "keywords": ["hasbro", "toys"]},
    "MAT": {"en": "Mattel", "zh": "美泰", "keywords": ["mattel", "barbie", "toys"]},
    "NWSA": {"en": "News Corp (Class A)", "zh": "新闻集团(A类)", "keywords": ["news corp", "media"]},
    "NWS": {"en": "News Corp", "zh": "新闻集团", "keywords": ["news corp", "media"]},
    "NXST": {"en": "Nexstar Media", "zh": "Nexstar媒体", "keywords": ["nexstar", "broadcasting"]},
    "PARA": {"en": "Paramount Global", "zh": "派拉蒙", "keywords": ["paramount", "cbs", "media"]},
    "WBD": {"en": "Warner Bros. Discovery", "zh": "华纳兄弟探索", "keywords": ["warner", "discovery", "media"]},
    "TTWO": {"en": "Take-Two Interactive", "zh": "Take-Two", "keywords": ["take two", "gta", "rockstar"]},
    "ATVI": {"en": "Activision Blizzard", "zh": "动视暴雪", "keywords": ["activision", "blizzard", "call of duty"]},
    "EA": {"en": "Electronic Arts", "zh": "艺电", "keywords": ["ea", "electronic arts", "fifa", "madden"]},
    # S&P 500 Components - Communication Services
    "META": {"en": "Meta", "zh": "Meta", "keywords": ["meta", "facebook", "instagram", "whatsapp"]},
    "GOOGL": {"en": "Google", "zh": "谷歌", "keywords": ["google", "alphabet", "search"]},
    "NFLX": {"en": "Netflix", "zh": "奈飞", "keywords": ["netflix", "streaming"]},
    "CMCSA": {"en": "Comcast", "zh": "康卡斯特", "keywords": ["comcast", "nbcuniversal", "xfinity"]},
    "T": {"en": "AT&T", "zh": "AT&T", "keywords": ["at&t", "att", "telecom"]},
    "VZ": {"en": "Verizon", "zh": "威瑞森", "keywords": ["verizon", "telecom"]},
    "TMUS": {"en": "T-Mobile", "zh": "T-Mobile", "keywords": ["t-mobile", "telecom"]},
    "CHTR": {"en": "Charter Communications", "zh": "特许通讯", "keywords": ["charter", "spectrum"]},
    "EA": {"en": "Electronic Arts", "zh": "艺电", "keywords": ["ea", "electronic arts", "fifa", "madden"]},
    "TTWO": {"en": "Take-Two Interactive", "zh": "Take-Two", "keywords": ["take two", "gta", "rockstar"]},
    "OMC": {"en": "Omnicom Group", "zh": "宏盟集团", "keywords": ["omnicom", "advertising"]},
    "IPG": {"en": "Interpublic Group", "zh": "埃培智", "keywords": ["interpublic", "advertising"]},
    "NFLX": {"en": "Netflix", "zh": "奈飞", "keywords": ["netflix", "streaming"]},
    "DIS": {"en": "Walt Disney", "zh": "迪士尼", "keywords": ["disney", "entertainment"]},
    "WBD": {"en": "Warner Bros. Discovery", "zh": "华纳兄弟探索", "keywords": ["warner", "discovery", "media"]},
    "PARA": {"en": "Paramount Global", "zh": "派拉蒙", "keywords": ["paramount", "cbs", "media"]},
    "FOXA": {"en": "Fox Corporation (Class A)", "zh": "福克斯(A类)", "keywords": ["fox", "media"]},
    "LYV": {"en": "Live Nation", "zh": "Live Nation", "keywords": ["live nation", "concerts"]},
    "MTCH": {"en": "Match Group", "zh": "Match集团", "keywords": ["match", "tinder", "dating"]},
    "PINS": {"en": "Pinterest", "zh": "Pinterest", "keywords": ["pinterest"]},
    "SNAP": {"en": "Snap Inc.", "zh": "Snap", "keywords": ["snapchat", "snap"]},
    "TWLO": {"en": "Twilio", "zh": "Twilio", "keywords": ["twilio"]},
    "ZM": {"en": "Zoom", "zh": "Zoom", "keywords": ["zoom"]},
    # S&P 500 Components - Industrials
    "GE": {"en": "General Electric", "zh": "通用电气", "keywords": ["general electric", "ge"]},
    "HON": {"en": "Honeywell", "zh": "霍尼韦尔", "keywords": ["honeywell"]},
    "UNP": {"en": "Union Pacific", "zh": "联合太平洋", "keywords": ["union pacific", "railroad"]},
    "CAT": {"en": "Caterpillar", "zh": "卡特彼勒", "keywords": ["caterpillar", "construction"]},
    "RTX": {"en": "RTX Corporation", "zh": "RTX", "keywords": ["rtx", "raytheon", "defense"]},
    "BA": {"en": "Boeing", "zh": "波音", "keywords": ["boeing", "aircraft"]},
    "DE": {"en": "Deere & Company", "zh": "约翰迪尔", "keywords": ["deere", "john deere", "agriculture"]},
    "LMMM": {"en": "3M", "zh": "3M", "keywords": ["3m", "post-it", "scotch"]},
    "UPS": {"en": "United Parcel Service", "zh": "联合包裹", "keywords": ["ups", "shipping"]},
    "ADP": {"en": "Automatic Data Processing", "zh": "自动数据处理", "keywords": ["adp", "payroll"]},
    "ITW": {"en": "Illinois Tool Works", "zh": "伊利诺伊工具", "keywords": ["illinois tool", "itw"]},
    "ETN": {"en": "Eaton", "zh": "伊顿", "keywords": ["eaton", "power management"]},
    "EMR": {"en": "Emerson Electric", "zh": "艾默生", "keywords": ["emerson", "automation"]},
    "ROK": {"en": "Rockwell Automation", "zh": "罗克韦尔自动化", "keywords": ["rockwell", "automation"]},
    "PH": {"en": "Parker Hannifin", "zh": "派克汉尼汾", "keywords": ["parker", "hydraulics"]},
    "GD": {"en": "General Dynamics", "zh": "通用动力", "keywords": ["general dynamics", "defense"]},
    "NOC": {"en": "Northrop Grumman", "zh": "诺斯罗普格鲁曼", "keywords": ["northrop", "defense"]},
    "LMT": {"en": "Lockheed Martin", "zh": "洛克希德马丁", "keywords": ["lockheed", "defense"]},
    "FDX": {"en": "FedEx", "zh": "联邦快递", "keywords": ["fedex", "shipping"]},
    "CSX": {"en": "CSX Corporation", "zh": "CSX运输", "keywords": ["csx", "railroad"]},
    "NSC": {"en": "Norfolk Southern", "zh": "诺福克南方", "keywords": ["norfolk southern", "railroad"]},
    "WM": {"en": "Waste Management", "zh": "废物管理", "keywords": ["waste management", "recycling"]},
    "RSG": {"en": "Republic Services", "zh": "共和服务", "keywords": ["republic", "waste"]},
    "CTAS": {"en": "Cintas Corporation", "zh": "辛塔斯", "keywords": ["cintas", "uniforms"]},
    "PCAR": {"en": "PACCAR", "zh": "帕卡", "keywords": ["paccar", "kenworth", "peterbilt"]},
    "ODFL": {"en": "Old Dominion Freight Line", "zh": "老自治领货运", "keywords": ["old dominion", "trucking"]},
    "FAST": {"en": "Fastenal", "zh": "快扣", "keywords": ["fastenal", "industrial supply"]},
    "GWW": {"en": "W.W. Grainger", "zh": "格兰杰", "keywords": ["grainger", "industrial supply"]},
    "SWK": {"en": "Stanley Black & Decker", "zh": "史丹利百得", "keywords": ["stanley", "black decker", "tools"]},
    "SNA": {"en": "Snap-on", "zh": "实耐宝", "keywords": ["snap-on", "tools"]},
    "FTV": {"en": "Fortive", "zh": "福迪威", "keywords": ["fortive", "instrumentation"]},
    "J": {"en": "Jacobs Solutions", "zh": "雅各布斯", "keywords": ["jacobs", "engineering"]},
    "PWR": {"en": "Quanta Services", "zh": "匡腾服务", "keywords": ["quanta", "infrastructure"]},
    "ACM": {"en": "AECOM", "zh": "AECOM", "keywords": ["aecom", "infrastructure"]},
    "AME": {"en": "AMETEK", "zh": "阿美特克", "keywords": ["ametek", "instruments"]},
    "DOW": {"en": "Dow Inc.", "zh": "陶氏化学", "keywords": ["dow", "chemicals"]},
    "DD": {"en": "DuPont", "zh": "杜邦", "keywords": ["dupont", "chemicals"]},
    "PPG": {"en": "PPG Industries", "zh": "PPG工业", "keywords": ["ppg", "coatings"]},
    "SHW": {"en": "Sherwin-Williams", "zh": "宣伟", "keywords": ["sherwin", "paint"]},
    "EMN": {"en": "Eastman Chemical", "zh": "伊士曼化工", "keywords": ["eastman", "chemicals"]},
    "CE": {"en": "Celanese", "zh": "塞拉尼斯", "keywords": ["celanese", "chemicals"]},
    "ALB": {"en": "Albemarle", "zh": "雅保", "keywords": ["albemarle", "lithium"]},
    "ECL": {"en": "Ecolab", "zh": "艺康", "keywords": ["ecolab", "cleaning"]},
    "APD": {"en": "Air Products", "zh": "空气化工", "keywords": ["air products", "industrial gas"]},
    "LIN": {"en": "Linde", "zh": "林德", "keywords": ["linde", "industrial gas"]},
    "FCX": {"en": "Freeport-McMoRan", "zh": "自由港", "keywords": ["freeport", "copper", "mining"]},
    "NEM": {"en": "Newmont", "zh": "纽蒙特", "keywords": ["newmont", "gold", "mining"]},
    "NUE": {"en": "Nucor", "zh": "纽柯钢铁", "keywords": ["nucor", "steel"]},
    "STLD": {"en": "Steel Dynamics", "zh": "钢铁动态", "keywords": ["steel dynamics"]},
    "VMC": {"en": "Vulcan Materials", "zh": "火神材料", "keywords": ["vulcan", "aggregates"]},
    "MLM": {"en": "Martin Marietta", "zh": "马丁玛丽埃塔", "keywords": ["marietta", "aggregates"]},
    "BALL": {"en": "Ball Corporation", "zh": "波尔公司", "keywords": ["ball", "packaging"]},
    "AVY": {"en": "Avery Dennison", "zh": "艾利丹尼森", "keywords": ["avery", "labels"]},
    "IP": {"en": "International Paper", "zh": "国际纸业", "keywords": ["international paper"]},
    "PKG": {"en": "Packaging Corporation", "zh": "包装公司", "keywords": ["packaging corp"]},
    "SEE": {"en": "Sealed Air", "zh": "希悦尔", "keywords": ["sealed air", "bubble wrap"]},
    "CTA-PB": {"en": "EIDP Inc.", "zh": "EIDP", "keywords": ["eidp", "dupont"]},
    "EME": {"en": "EMCOR Group", "zh": "EMCOR", "keywords": ["emcor", "construction"]},
    "FIX": {"en": "Comfort Systems USA", "zh": "舒适系统", "keywords": ["comfort systems", "hvac"]},
    "GATX": {"en": "GATX Corporation", "zh": "GATX", "keywords": ["gatx", "railcars"]},
    "LSTR": {"en": "Landstar System", "zh": "朗斯塔", "keywords": ["landstar", "logistics"]},
    "JBHT": {"en": "J.B. Hunt", "zh": "亨特运输", "keywords": ["jb hunt", "trucking"]},
    "CHRW": {"en": "C.H. Robinson", "zh": "罗宾逊", "keywords": ["robinson", "logistics"]},
    "XPO": {"en": "XPO Logistics", "zh": "XPO物流", "keywords": ["xpo", "logistics"]},
    "EXPD": {"en": "Expeditors International", "zh": "飞协博", "keywords": ["expeditors", "freight"]},
    "HUBB": {"en": "Hubbell", "zh": "哈贝尔", "keywords": ["hubbell", "electrical"]},
    "GNRC": {"en": "Generac", "zh": "Generac", "keywords": ["generac", "generator"]},
    "SWK": {"en": "Stanley Black & Decker", "zh": "史丹利百得", "keywords": ["stanley", "black decker", "tools"]},
    "IR": {"en": "Ingersoll Rand", "zh": "英格索兰", "keywords": ["ingersoll rand", "compressor"]},
    "DOV": {"en": "Dover Corporation", "zh": "多佛", "keywords": ["dover", "industrial"]},
    "FDX": {"en": "FedEx", "zh": "联邦快递", "keywords": ["fedex", "shipping"]},
    # S&P 500 Components - Consumer Staples
    "PG": {"en": "Procter & Gamble", "zh": "宝洁", "keywords": ["procter gamble", "pg", "tide"]},
    "KO": {"en": "Coca-Cola", "zh": "可口可乐", "keywords": ["coca-cola", "coke"]},
    "PEP": {"en": "PepsiCo", "zh": "百事公司", "keywords": ["pepsi", "pepsico", "frito-lay"]},
    "COST": {"en": "Costco", "zh": "好市多", "keywords": ["costco", "wholesale"]},
    "WMT": {"en": "Walmart", "zh": "沃尔玛", "keywords": ["walmart"]},
    "PM": {"en": "Philip Morris", "zh": "菲利普莫里斯", "keywords": ["philip morris", "tobacco"]},
    "MO": {"en": "Altria", "zh": "奥驰亚", "keywords": ["altria", "tobacco"]},
    "CL": {"en": "Colgate-Palmolive", "zh": "高露洁", "keywords": ["colgate", "toothpaste"]},
    "KMB": {"en": "Kimberly-Clark", "zh": "金佰利", "keywords": ["kimberly-clark", "kleenex"]},
    "SYY": {"en": "Sysco", "zh": "西斯科", "keywords": ["sysco", "food distribution"]},
    "ADM": {"en": "Archer-Daniels-Midland", "zh": "ADM", "keywords": ["adm", "agriculture"]},
    "CAG": {"en": "Conagra Brands", "zh": "康尼格拉", "keywords": ["conagra", "food"]},
    "CPB": {"en": "Campbell Soup", "zh": "金宝汤", "keywords": ["campbell", "soup"]},
    "GIS": {"en": "General Mills", "zh": "通用磨坊", "keywords": ["general mills", "cereal"]},
    "HSY": {"en": "Hershey", "zh": "好时", "keywords": ["hershey", "chocolate"]},
    "K": {"en": "Kellogg's", "zh": "家乐氏", "keywords": ["kellogg", "cereal"]},
    "KHC": {"en": "Kraft Heinz", "zh": "卡夫亨氏", "keywords": ["kraft", "heinz", "food"]},
    "MKC": {"en": "McCormick", "zh": "味好美", "keywords": ["mccormick", "spices"]},
    "SJM": {"en": "J.M. Smucker", "zh": "盛美家", "keywords": ["smucker", "jelly"]},
    "TSN": {"en": "Tyson Foods", "zh": "泰森食品", "keywords": ["tyson", "chicken"]},
    "HRL": {"en": "Hormel Foods", "zh": "荷美尔", "keywords": ["hormel", "spam"]},
    "MDLZ": {"en": "Mondelez International", "zh": "亿滋国际", "keywords": ["mondelez", "oreo", "cadbury"]},
    "MNST": {"en": "Monster Beverage", "zh": "怪兽饮料", "keywords": ["monster", "energy drink"]},
    "KDP": {"en": "Keurig Dr Pepper", "zh": "胡椒博士", "keywords": ["keurig", "dr pepper", "coffee"]},
    "STZ": {"en": "Constellation Brands", "zh": "星座品牌", "keywords": ["constellation", "beer", "corona"]},
    "BF.B": {"en": "Brown-Forman", "zh": "百富门", "keywords": ["brown-forman", "jack daniels"]},
    "DEO": {"en": "Diageo", "zh": "帝亚吉欧", "keywords": ["diageo", "guinness", "johnnie walker"]},
    "CLX": {"en": "Clorox", "zh": "高乐氏", "keywords": ["clorox", "bleach"]},
    "CHD": {"en": "Church & Dwight", "zh": "切奇杜威", "keywords": ["church dwight", "arm hammer"]},
    "EL": {"en": "Estée Lauder", "zh": "雅诗兰黛", "keywords": ["estee lauder", "cosmetics"]},
    "KMB": {"en": "Kimberly-Clark", "zh": "金佰利", "keywords": ["kimberly-clark", "kleenex"]},
    "COTY": {"en": "Coty", "zh": "科蒂", "keywords": ["coty", "cosmetics"]},
    "PG": {"en": "Procter & Gamble", "zh": "宝洁", "keywords": ["procter gamble", "pg", "tide"]},
    "WBA": {"en": "Walgreens Boots Alliance", "zh": "沃博联", "keywords": ["walgreens", "pharmacy"]},
    # S&P 500 Components - Energy
    "XOM": {"en": "ExxonMobil", "zh": "埃克森美孚", "keywords": ["exxon", "mobil", "oil"]},
    "CVX": {"en": "Chevron", "zh": "雪佛龙", "keywords": ["chevron", "oil"]},
    "COP": {"en": "ConocoPhillips", "zh": "康菲石油", "keywords": ["conoco", "oil"]},
    "SLB": {"en": "Schlumberger", "zh": "斯伦贝谢", "keywords": ["schlumberger", "oilfield"]},
    "EOG": {"en": "EOG Resources", "zh": "EOG资源", "keywords": ["eog", "oil"]},
    "MPC": {"en": "Marathon Petroleum", "zh": "马拉松石油", "keywords": ["marathon", "refining"]},
    "PSX": {"en": "Phillips 66", "zh": "菲利普斯66", "keywords": ["phillips 66", "refining"]},
    "VLO": {"en": "Valero Energy", "zh": "瓦莱罗能源", "keywords": ["valero", "refining"]},
    "OXY": {"en": "Occidental Petroleum", "zh": "西方石油", "keywords": ["occidental", "oil"]},
    "HAL": {"en": "Halliburton", "zh": "哈利伯顿", "keywords": ["halliburton", "oilfield"]},
    "DVN": {"en": "Devon Energy", "zh": "德文能源", "keywords": ["devon", "oil"]},
    "FANG": {"en": "Diamondback Energy", "zh": "响尾蛇能源", "keywords": ["diamondback", "oil", "permian"]},
    "PXD": {"en": "Pioneer Natural Resources", "zh": "先锋自然资源", "keywords": ["pioneer", "oil"]},
    "HES": {"en": "Hess", "zh": "赫斯", "keywords": ["hess", "oil"]},
    "MRO": {"en": "Marathon Oil", "zh": "马拉松石油", "keywords": ["marathon oil"]},
    "APA": {"en": "APA Corporation", "zh": "APA公司", "keywords": ["apa", "oil"]}

}

_config: Optional[Dict] = None


def _load_config() -> Dict:
    global _config
    if _config is not None:
        return _config
    return _DEFAULT_CONFIG


def reload_config(config_path: Optional[str] = None) -> Dict:
    """从外部 JSON 文件加载配置以覆盖默认值；传 None 则恢复默认。"""
    global _config
    if config_path is None:
        _config = None
        return _DEFAULT_CONFIG
    with open(config_path, "r", encoding="utf-8") as f:
        _config = json.load(f)
    return _config


def get_company_name_en(ticker: str, fallback: Optional[str] = None) -> str:
    """获取美股公司英文名称。"""
    config = _load_config()
    entry = config.get(ticker.upper())
    if entry:
        return entry["en"]
    return fallback if fallback is not None else f"US:{ticker}"


def get_company_name_zh(ticker: str, fallback: Optional[str] = None) -> str:
    """获取美股公司中文名称。"""
    config = _load_config()
    entry = config.get(ticker.upper())
    if entry:
        return entry["zh"]
    return fallback if fallback is not None else f"美股{ticker}"


def get_search_keywords(ticker: str) -> List[str]:
    """获取股票代码对应的搜索关键词列表（用于新闻相关性匹配）。"""
    config = _load_config()
    entry = config.get(ticker.upper()) or config.get(ticker.lower())
    if entry:
        return entry.get("keywords", [])
    return []


def get_search_string(ticker: str) -> str:
    """获取用于新闻搜索的 OR 分隔字符串。例如 "Apple" 或 "Meta OR Facebook"。"""
    config = _load_config()
    entry = config.get(ticker.upper())
    if entry:
        keywords = entry.get("keywords", [])
        if keywords:
            return " OR ".join(k.capitalize() for k in keywords)
        return entry["en"]
    return ticker


def get_all_tickers() -> List[str]:
    """获取所有已配置的股票代码列表。"""
    return list(_load_config().keys())


def get_keywords_map(ticker: str) -> Dict[str, List[str]]:
    """获取小写 ticker -> 关键词列表的映射。"""
    config = _load_config()
    entry = config.get(ticker.upper())
    if entry:
        return {ticker.lower(): entry.get("keywords", [])}
    return {}
